# Generated by Django 2.1.15 on 2020-05-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_category',
            name='user_category',
            field=models.CharField(choices=[('S', 'Student'), ('P', 'Parent'), ('T', 'Teacher'), ('M', 'Management')], max_length=1),
        ),
    ]
