# Generated by Django 2.1.15 on 2020-05-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('staffid', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('staffname', models.CharField(max_length=100)),
                ('desg', models.CharField(max_length=250)),
                ('depcode', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('mobile', models.CharField(max_length=250)),
                ('post', models.CharField(max_length=250)),
                ('sesid', models.CharField(max_length=250)),
                ('sesno', models.IntegerField()),
            ],
        ),
    ]
